### ISSUE TITLE
Can't change main logger parameters

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/graphviper#16]
Minimal example:
```
import graphviper.utils.logger as logger
from graphviper.dask.client import local_client

log_params = {"logger_name": "client",
            "log_to_term": True,
            "log_level": "DEBUG", #Change to DEBUG 
            "log_to_file": False,
            "log_file": None,}

viper_client = local_client(cores=2, memory_limit="4GiB",log_params=log_params)

logger.debug("Hallo")
logger.info("Hallo")
```
Only info Hallo is printed even though level is changed to debug.

**Comment by jrhosk** [comment]
This is actually working as intended and you **can** get the debug logger. What you did above was setup the logger for the internal code within the client (and other code that calls the "client" logger). this is done automatically inside code, where the logger is implemented, by setting up an environment variable "VIPER_LOGGER_NAME". When ever the code calls `logger.debug("Hallo")` within the code it will get the logger name from the environment variable and return that logger. This is done to obfuscate having to call `get_logger()` in the code all the time. If you don't use it this way you will get a default logger back when you make the call to `logger.LEVEL`; you will notice when running your code from above you get a logger name that isn't client. Fear not! It is easy to use the logger you setup in this case by simply doing the following:

`logger.get_logger("client").debug("Hallo")`

or if this is too much trouble, add the following to your notebook under the client call:

`os.environ["VIPER_LOGGER_NAME"] = "client"`

![grapviper](https://github.com/casangi/graphviper/assets/2530451/3960f11a-c6ed-4133-bf8c-88f2d6761250)

@Jan-Willem

**Comment by Jan-Willem** [comment]
The default in client.py is the client logger and changing its level to debug does not show:  
```
logger.debug(f"These are the worker log parameters:\n {worker_log_params}")
```
I assume this is the case since that statement is being sent to the graphviper logger.

@jrhosk Why do we have a separate logger for graphviper and client? They run in the same Python process. 

The local_client parameters suggests to the user that there are only two logger setups they need to worry about. For example, if I wanted to change graphviper and client logger setup, how would I do it using local_client?

**Comment by jrhosk** [comment]
Here is the reconfigure solution. You will notice that the code starts with `graphviper` because the parameter checking runs before that client logger is setup. Afterwards, everything should work with the user specified logger.

![graphviper_tois](https://github.com/casangi/graphviper/assets/2530451/de29f4dd-d587-47a2-99cf-983d0bd2798c)

**Comment by jrhosk** [comment]
On another note, could you confirm the sharing link information (or invite me to the dropbox with it) for file `Antennae_North.cal.lsrk.split.vis.zarr`, the fiel that is being downloaded seems to be incorrect and this is something I have not touched but is causing the tests to fail.

@Jan-Willem

**Comment by Jan-Willem** [comment]
@jrhosk Thanks. I have no preference to what the default logger is called (the client.py code suggested that it was called client). I will give the code in [13-update-client-docs-and-allow-logging-with-serial-execution] a try.

**Comment by jrhosk** [comment]
Sounds good! I want it to work in an intuitive way, so thanks for bringing it up. I can make more changes if you would like.
