### ISSUE TITLE
Refactor Parameter Checker

### ISSUE THREAD

**Issue by Jan-Willem** [casangi/graphviper#2]
- [x] Move the parameter checking code that AstroHACK uses to GraphVIPER. 
- [x] Add parameter checking to https://github.com/casangi/graphviper/blob/main/src/graphviper/dask/client.py
- [x] Ensure that AstroVIPER ipynb in https://github.com/casangi/astroviper/tree/main/docs work.
- [x] Add unit tests

**Comment by jrhosk** [comment]
This was also fixed by PR https://github.com/casangi/graphviper/pull/5. Closing : )
